<?php

namespace App\Http\Resources\ImageTemplate;

use Illuminate\Http\Resources\Json\JsonResource;

class ImageTemplateItemResource extends JsonResource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
