name: Frontend Next CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'Warning'

jobs:
  frontend-node-install:

    runs-on: Ubuntu-latest
    env:
      node-version: "19.7.0"
      nvm-version: 0.31.1

    steps:
    - uses: actions/checkout@v3
    - name: Install NVM
      run: |
          sudo apt-get update
          sudo apt-get install build-essential libssl-dev
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v${{ env.nvm-version }}/install.sh | bash source ~/.profile
          ls
          #nvm ls-remote
          #
    #Install node.js ${{ env.node-version }}
      #run: sudo apt install nodejs
    - name: Use node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
