name: Frontend Next CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'Warning'

env:
  node-version: "19.7.0"

jobs:


  frontend-next-public:
    #needs: frontend-node-install
    runs-on: Ubuntu-latest

    defaults:
      run:
        working-directory: ./next

    steps:
    - run: pwd
      #- name: Install Dependencies
       # shell: bash -l {0}
        #run: |
         # nvm use ${{ env.node-version }}
          #ls

      #- name: Check installed dependencies
       # shell: bash -l {0}
        #run: |
         # node -v
          #npm -v
          #npm list
    
    #Install node.js ${{ env.node-version }}
      #run: sudo apt install nodejs
    #- name: Use node.js ${{ env.node-version }}
     # uses: actions/setup-node@v3
      #with:
       # node-version: ${{ env.node-version }}
        #cache: 'npm'
          #npm install
