name: Frontend Next CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'Warning'

jobs:
  frontend-node-install:

    runs-on: Ubuntu-latest
    env:
      node-version: "19.7.0"

    steps:
    - uses: actions/checkout@v3
    - name: Enable and check NVM version
      run: |
        echo "[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh" >> $HOME/.profile
        source ~/.profile
        nvm -v
      shell: bash -l {0}
    - name: Install Node.js ${{ env.node-version }}
      shell: bash -l {0}
      run: nvm install ${{ env.node-version }}
    - name: Check Node.js version and NPM
      run: |
        node -v
        npm -v
    #Install node.js ${{ env.node-version }}
      #run: sudo apt install nodejs
    #- name: Use node.js ${{ env.node-version }}
     # uses: actions/setup-node@v3
      #with:
       # node-version: ${{ env.node-version }}
        #cache: 'npm'
