name: Frontend Next Public

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'Warning'
      tags:
        description: 'Test scenario tags'

jobs:
  frontend-next-public:

    runs-on: Ubuntu-latest

    env:
      node-version: "19.7.0"

    defaults:
      run:
        working-directory: ./next

    steps:
    - uses: actions/checkout@v3
    - run: pwd
          
