name: Frontend Next CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'Warning'

env:
  node-version: "19.7.0"

jobs:
  frontend-node-install:
    runs-on: Ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Enable and check NVM version
      run: |
        echo "[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh" >> $HOME/.profile
        source ~/.profile
        nvm -v
      shell: bash -l {0}
    - name: Install Node.js ${{ env.node-version }}
      shell: bash -l {0}
      run: |
        nvm install ${{ env.node-version }}
    - name: Check Node.js version and NPM
      shell: bash -l {0}
      run: |
        nvm use ${{ env.node-version }}
        node -v
        npm -v

  frontend-next-admin:
    needs: frontend-node-install
    runs-on: Ubuntu-latest

    defaults:
      run:
        working-directory: /next-admin

    steps:
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          nvm use ${{ env.node-version }}
          npm install
      - name: Check installed dependencies
        shell: bash -l {0}
        run: |
          node -v
          npm -v
          npm list
    
    #Install node.js ${{ env.node-version }}
      #run: sudo apt install nodejs
    #- name: Use node.js ${{ env.node-version }}
     # uses: actions/setup-node@v3
      #with:
       # node-version: ${{ env.node-version }}
        #cache: 'npm'
